spring:
  application:
    name: r-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  datasource:
    username: r_pan
    password: YR56hK5NdwEWtP8A
    url: jdbc:mysql://47.113.216.13:3306/r_pan?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #数据库索引
    database: 1
    host: 47.113.216.13
    port: 6379
    password: Hujing123

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080

logging:
  file: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.imooc.pan.server.modules
  title: r-pan-server docs
  description: r-pan-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: imooc
  contact-url: https://blog.imoocchu.com
  contact-email: imoocchu@126.com
  version: 1.0



  #配置存储引擎,不配走默认本地
#com:
#  imooc:
#    pan:
#      storage:
#        engine:
#          fdfs:
#            connect-timeout: 600
#            tracker-list:
#              - 47.113.216.13:22122
#            group: group1

